# encoding: utf-8

# Pretty-printers for Boost (http://www.boost.org)

# Copyright (C) 2009 Rüdiger Sonderfeld <ruediger@c-plusplus.de>

# Boost Software License - Version 1.0 - August 17th, 2003

# Permission is hereby granted, free of charge, to any person or organization
# obtaining a copy of the software and accompanying documentation covered by
# this license (the "Software") to use, reproduce, display, distribute,
# execute, and transmit the Software, and to prepare derivative works of the
# Software, and to permit third-parties to whom the Software is furnished to
# do so, all subject to the following:

# The copyright notices in the Software and this entire statement, including
# the above license grant, this restriction and the following disclaimer,
# must be included in all copies of the Software, in whole or in part, and
# all derivative works of the Software, unless such copies or derivative
# works are solely in the form of machine-executable object code generated by
# a source language processor.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
# SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
# FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

#
# Inspired _but not copied_ from libstdc++'s pretty printers
#

import gdb
import re

class static:
    "Creates a 'static' method"
    def __init__(self, function):
        self.__call__ = function

boost_pretty_printers = [ ]
def register_pretty_printer(pretty_printer):
    "Registers a Pretty Printer"
    boost_pretty_printers.append(pretty_printer)
    return pretty_printer

@register_pretty_printer
class BoostIteratorRange:
    "Pretty Printer for boost::iterator_range (Boost.Range)"
    @static
    def supports(typename):
        return re.compile('^boost::iterator_range<.*>$').search(typename)

    class _iterator:
        def __init__(self, begin, end):
            self.item = begin
            self.end = end
            self.count = 0

        def __iter__(self):
            return self

        def next(self):
            if self.item == self.end:
                raise StopIteration
            count = self.count
            self.count = self.count + 1
            elem = self.item.dereference()
            self.item = self.item + 1
            return ('[%d]' % count, elem)

    def __init__(self, typename, value):
        self.typename = typename
        self.value = value

    def children(self):
        return self._iterator(self.value['m_Begin'], self.value['m_End'])

    def to_string(self):
        begin = self.value['m_Begin']
        end = self.value['m_End']
        return '%s of length %d' % (self.typename, int(end - begin))

    def display_hint(self):
        return 'array'

@register_pretty_printer
class BoostOptional:
    "Pretty Printer for boost::optional (Boost.Optional)"
    regex = re.compile('^boost::optional<(.*)>$')

    @static
    def supports(typename):
        return BoostOptional.regex.search(typename)

    def __init__(self, typename, value):
        self.typename = typename
        self.value = value

    class _iterator:
        def __init__(self, member, empty):
            self.member = member
            self.done = empty

        def __iter__(self):
            return self

        def next(self):
            if(self.done):
                raise StopIteration
            self.done = True
            return ('value', self.member.dereference())

    def children(self):
        initialized = self.value['m_initialized']
        if(not initialized):
            return self._iterator('', True)
        else:
            match = BoostOptional.regex.search(self.typename)
            if match:
                try:
                    membertype = gdb.lookup_type(match.group(1)).pointer()
                    member = self.value['m_storage']['dummy_']['data'].address.cast(membertype)
                    return self._iterator(member, False)
                except:
                    return self._iterator('', True)

    def to_string(self):
        initialized = self.value['m_initialized']
        if(not initialized):
            return "%s is not initialized" % self.typename
        else:
            return "%s is initialized" % self.typename

@register_pretty_printer
class BoostReferenceWrapper:
    "Pretty Printer for boost::reference_wrapper (Boost.Ref)"
    regex = re.compile('^boost::reference_wrapper<(.*)>$')

    @static
    def supports(typename):
        return BoostReferenceWrapper.regex.search(typename)

    def __init__(self, typename, value):
        self.typename = typename
        self.value = value

    def to_string(self):
        return '(%s) %s' % (self.typename, self.value['t_'].dereference())

@register_pretty_printer
class BoostTribool:
    "Pretty Printer for boost::logic::tribool (Boost.Tribool)"
    regex = re.compile('^boost::logic::tribool$')

    @static
    def supports(typename):
        return BoostTribool.regex.search(typename)

    def __init__(self, typename, value):
        self.typename = typename
        self.value = value

    def to_string(self):
        state = self.value['value']
        s = 'indeterminate'
        if(state == 0):
            s = 'false'
        elif(state == 1):
            s = 'true'
        return '(%s) %s' % (self.typename, s)

@register_pretty_printer
class BoostScopedPtr:
    "Pretty Printer for boost::scoped/intrusive_ptr/array (Boost.SmartPtr)"

    regex = re.compile('^boost::(intrusive|scoped)_(ptr|array)<(.*)>$')
    @static
    def supports(typename):
        return BoostScopedPtr.regex.search(typename)

    def __init__(self, typename, value):
        self.typename = typename
        self.value = value

    def to_string(self):
        return '(%s) %s' % (self.typename, self.value['px'])

@register_pretty_printer
class BoostSharedPtr:
    "Pretty Printer for boost::shared/weak_ptr/array (Boost.SmartPtr)"

    regex = re.compile('^boost::(weak|shared)_(ptr|array)<(.*)>$')
    @static
    def supports(typename):
        return BoostSharedPtr.regex.search(typename)

    def __init__(self, typename, value):
        self.typename = typename
        self.value = value

    def to_string(self):
        if self.value['px'] == 0x0:
            return '(%s) %s' % (self.typename, self.value['px'])
        countobj = self.value['pn']['pi_'].dereference()
        refcount = countobj['use_count_']
        weakcount = countobj['weak_count_']
        return '(%s) (count %d, weak count %d) %s' % (self.typename,
                                                      refcount, weakcount,
                                                      self.value['px'])

@register_pretty_printer
class BoostArray:
    "Pretty Printer for boost::array (Boost.Array)"
    regex = re.compile('^boost::array<(.*)>$');
    @static
    def supports(typename):
        return BoostArray.regex.search(typename)

    def __init__(self, typename, value):
        self.typename = typename
        self.value = value

    def to_string(self):
        return self.value['elems']

    def display_hint(self):
        return 'array'

@register_pretty_printer
class BoostVariant:
    "Pretty Printer for boost::variant (Boost.Variant)"
    regex = re.compile('^boost::variant<(.*)>$');
    @static
    def supports(typename):
        return BoostVariant.regex.search(typename)

    def __init__(self, typename, value):
        self.typename = typename
        self.value = value

    def to_string(self):
        m = BoostVariant.regex.search(self.typename)
        # TODO this breaks with boost::variant< foo<a,b>, bar >!
        types = map(lambda s: s.strip(), m.group(1).split(','))
        which = long(self.value['which_'])
        type = types[which]
        data = ''
        try:
            ptrtype = gdb.lookup_type(type).pointer()
            data = self.value['storage_']['data_']['buf'].address.cast(ptrtype)
        except:
            data = self.value['storage_']['data_']['buf']
        return '(boost::variant<...>) which (%d) = %s value = %s' % (which,
                                                                     type,
                                                                     data.dereference())

@register_pretty_printer
class BoostUuid:
    "Pretty Printer for boost::uuids::uuid (Boost.Uuid)"
    regex = re.compile('^boost::uuids::uuid$')

    @static
    def supports(typename):
        return BoostUuid.regex.search(typename)

    def __init__(self, typename, value):
        self.typename = typename
        self.value = value

    def to_string(self):
        u = (self.value['data'][i] for i in xrange(16))
        s = 'xxxx-xx-xx-xx-xxxxxx'.replace('x', '%02x') % tuple(u)
        return '(%s) %s' % (self.typename, s)

##################################################
# boost::intrusive::set                          #
##################################################

def get_named_template_argument(gdb_type, arg_name):
    n = 0;
    while True:
        try:
            arg = gdb_type.strip_typedefs().template_argument(n)
            if (str(arg).startswith(arg_name)):
                return arg
            n += 1
        except RuntimeError:
            return None

def intrusive_container_has_size_member(intrusive_container_type):
    constant_size_arg = get_named_template_argument(intrusive_container_type, "boost::intrusive::constant_time_size")
    if not constant_size_arg:
        return True
    if str(constant_size_arg.template_argument(0)) == 'false':
        return False
    return True

def intrusive_iterator_to_string(iterator_value):
    opttype = iterator_value.type.template_argument(0).template_argument(0)

    base_hook_traits = get_named_template_argument(opttype, "boost::intrusive::detail::base_hook_traits")
    if base_hook_traits:
        value_type = base_hook_traits.template_argument(0)
        return iterator_value["members_"]["nodeptr_"].cast(value_type.pointer()).dereference()

    member_hook_traits = get_named_template_argument(opttype, "boost::intrusive::detail::member_hook_traits")
    if member_hook_traits:
        value_type = member_hook_traits.template_argument(0)
        member_offset = member_hook_traits.template_argument(2).cast(gdb.lookup_type("size_t"))
        currentElementAddress = iterator_value["members_"]["nodeptr_"].cast(gdb.lookup_type("size_t")) - member_offset
        return currentElementAddress.cast(value_type.pointer()).dereference()

    return iterator_value["members_"]["nodeptr_"]


class BoostIntrusiveRbtreeIterator:
    def __init__(self, rbTreeHeader, elementPointerType, memberOffset=0):
        self.header = rbTreeHeader
        self.memberOffset = memberOffset
        if memberOffset == 0:
            self.nodeType = elementPointerType
        else:
            self.nodeType = gdb.lookup_type("boost::intrusive::rbtree_node<void*>").pointer();
            self.elementPointerType = elementPointerType
        self.node = rbTreeHeader['left_'].cast(self.nodeType)

    def __iter__(self):
        return self

    def getElementPointerFromNodePointer(self):
        if self.memberOffset == 0:
            return self.node
        else:
            currentElementAddress = self.node.cast(gdb.lookup_type("size_t")) - self.memberOffset
            return currentElementAddress.cast(self.elementPointerType)

    def next(self):
        # empty set or reached rightmost leaf
        if not self.node:
            raise StopIteration
        result = self.getElementPointerFromNodePointer()
        if self.node != self.header["right_"].cast(self.nodeType):
            # Compute the next node.
            node = self.node
            if node.dereference()['right_']:
                node = node.dereference()['right_']
                while node.dereference()['left_']:
                    node = node.dereference()['left_']
            else:
                parent = node.dereference()['parent_']
                while node == parent.dereference()['right_']:
                    node = parent
                    parent = parent.dereference()['parent_']
                if node.dereference()['right_'] != parent:
                    node = parent
            self.node = node.cast(self.nodeType)
        else:
            self.node = 0
        return result

@register_pretty_printer
class BoostIntrusiveSet:
    "Pretty Printer for boost::intrusive::set (Boost.Intrusive)"
    regex = re.compile('^boost::intrusive::set<.*>$');

    @static
    def supports(typename):
        return BoostIntrusiveSet.regex.search(typename)

    class _iter:
        def __init__(self, rbiter):
            self.rbiter = rbiter
            self.count = 0

        def __iter__(self):
            return self

        def next(self):
            item = self.rbiter.next().dereference()
            result = ('[%d]' % self.count, item)
            self.count = self.count + 1
            return result

    def __init__(self, typename, value):
        self.typename = typename
        self.val = value
        self.elementType = self.val.type.strip_typedefs().template_argument(0)

    def getHeader(self):
        return self.val["tree_"]["data_"]["node_plus_pred_"]["header_plus_size_"]["header_"]

    def getSize(self):
        return self.val["tree_"]["data_"]["node_plus_pred_"]["header_plus_size_"]["size_"]

    def hasElements(self):
        header = self.getHeader()
        firstElement = header["parent_"]
        if firstElement:
            return True
        else:
            return False

    def to_string (self):
        if (intrusive_container_has_size_member(self.val.type)):
            return "boost::intrusive::set<%s> with %d elements" % (self.elementType, self.getSize())
        elif (self.hasElements()):
            return "non-empty boost::intrusive::set<%s>" % self.elementType
        else:
            return "empty boost::intrusive::set<%s>" % self.elementType

    def children (self):
        elementPointerType = self.elementType.pointer()
        member_hook = get_named_template_argument(self.val.type, "boost::intrusive::member_hook")
        if member_hook:
            memberOffset = member_hook.template_argument(2).cast(gdb.lookup_type("size_t"))
            return self._iter (BoostIntrusiveRbtreeIterator(self.getHeader(), elementPointerType, memberOffset))
        else:
            return self._iter (BoostIntrusiveRbtreeIterator(self.getHeader(), elementPointerType))


@register_pretty_printer
class BoostIntrusiveTreeIterator:
    "Pretty Printer for boost::intrusive::set<*>::iterator (Boost.Intrusive)"

    regex = re.compile('^boost::intrusive::tree_iterator<.*>$');

    @static
    def supports(typename):
        return BoostIntrusiveTreeIterator.regex.search(typename)

    def __init__(self, typename, val):
        self.val = val
        self.typename = typename

    def to_string(self):
        return intrusive_iterator_to_string(self.val)


##################################################
# boost::intrusive::list                         #
##################################################

class BoostIntrusiveListIterator:
    def __init__(self, listHeader, elementPointerType, memberOffset=0):
        self.header = listHeader
        self.memberOffset = memberOffset
        if memberOffset == 0:
            self.nodeType = elementPointerType
        else:
            self.nodeType = gdb.lookup_type("boost::intrusive::list_node<void*>").pointer();
            self.elementPointerType = elementPointerType
        nextNode = listHeader['next_']
        if nextNode != listHeader.address:
            self.node = nextNode.cast(self.nodeType)
        else:
            self.node = 0

    def __iter__(self):
        return self

    def getElementPointerFromNodePointer(self):
        if self.memberOffset == 0:
            return self.node
        else:
            currentElementAddress = self.node.cast(gdb.lookup_type("size_t")) - self.memberOffset
            return currentElementAddress.cast(self.elementPointerType)

    def next(self):
        # empty list or reached end
        if not self.node:
            raise StopIteration
        result = self.getElementPointerFromNodePointer()
        nextNode = self.node['next_']
        if nextNode != self.header.address:
            self.node = nextNode.cast(self.nodeType)
        else:
            self.node = 0
        return result

@register_pretty_printer
class BoostIntrusiveList:
    "Pretty Printer for boost::intrusive::list (Boost.Intrusive)"
    regex = re.compile('^boost::intrusive::list<.*>$');

    @static
    def supports(typename):
        return BoostIntrusiveList.regex.search(typename)

    class _iter:
        def __init__(self, listiter):
            self.listiter = listiter
            self.count = 0

        def __iter__(self):
            return self

        def next(self):
            item = self.listiter.next().dereference()
            result = ('[%d]' % self.count, item)
            self.count = self.count + 1
            return result

    def __init__(self, typename, value):
        self.typename = typename
        self.val = value
        self.elementType = self.val.type.strip_typedefs().template_argument(0)

    def getHeader(self):
        return self.val["data_"]["root_plus_size_"]["root_"]

    def getSize(self):
        return self.val["data_"]["root_plus_size_"]["size_"]

    def hasElements(self):
        header = self.getHeader()
        firstElement = header["next_"]
        rootElement = header.address
        if firstElement != rootElement:
            return True
        else:
            return False

    def to_string (self):
        if (intrusive_container_has_size_member(self.val.type)):
            return "boost::intrusive::list<%s> with %d elements" % (self.elementType, self.getSize())
        elif (self.hasElements()):
            return "non-empty boost::intrusive::list<%s>" % self.elementType
        else:
            return "empty boost::intrusive::list<%s>" % self.elementType

    def children (self):
        elementPointerType = self.elementType.pointer()
        member_hook = get_named_template_argument(self.val.type, "boost::intrusive::member_hook")
        if member_hook:
            memberOffset = member_hook.template_argument(2).cast(gdb.lookup_type("size_t"))
            return self._iter (BoostIntrusiveListIterator(self.getHeader(), elementPointerType, memberOffset))
        else:
            return self._iter (BoostIntrusiveListIterator(self.getHeader(), elementPointerType))

@register_pretty_printer
class BoostIntrusiveListIterator:
    "Pretty Printer for boost::intrusive::list<*>::iterator (Boost.Intrusive)"

    regex = re.compile('^boost::intrusive::list_iterator<.*>$');

    @static
    def supports(typename):
        return BoostIntrusiveListIterator.regex.search(typename)

    def __init__(self, typename, val):
        self.val = val
        self.typename = typename

    def to_string(self):
        return intrusive_iterator_to_string(self.val)

def find_pretty_printer(value):
    "Find a pretty printer suitable for value"
    type = value.type

    if type.code == gdb.TYPE_CODE_REF:
       type = type.target()

    type = type.unqualified().strip_typedefs()

    typename = type.tag
    if typename == None:
        return None

    for pretty_printer in boost_pretty_printers:
        if pretty_printer.supports(typename):
            return pretty_printer(typename, value)

    return None

@register_pretty_printer
class BoostGregorianDate:
    "Pretty Printer for boost::gregorian::date"
    regex = re.compile('^boost::gregorian::date$')

    @static
    def supports(typename):
        return BoostGregorianDate.regex.search(typename)

    def __init__(self, typename, value):
        self.typename = typename
        self.value = value

    def to_string(self):
        n = int(self.value['days_'])
        # Check for uninitialized case
        if n==2**32-2:
            return '(%s) uninitialized' % self.typename
        # Convert date number to year-month-day
        a = n + 32044
        b = (4*a + 3) / 146097
        c = a - (146097*b)/4
        d = (4*c + 3)/1461
        e = c - (1461*d)/4
        m = (5*e + 2)/153
        day = e + 1 - (153*m + 2)/5
        month = m + 3 - 12*(m/10)
        year = 100*b + d - 4800 + (m/10)
        return '(%s) %4d-%02d-%02d' % (self.typename, year,month,day)


def register_boost_printers(obj):
    "Register Boost Pretty Printers."
    if obj == None:
        obj = gdb
    obj.pretty_printers.append(find_pretty_printer)
