name: Unit tests
on: [push, pull_request]
jobs:
    unit_tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                boost_version: [1.50, 1.54, 1.55, 1.58, 1.65.1, 1.66, 1.69, 1.70]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/cache@v2
              with:
                key: boost-${{ matrix.boost_version }}
                path: tests/tmp/boost_*.tar.bz2
            - run: sudo apt-get install --yes gdb
            - run: python3 tests/run -c -b ${{ matrix.boost_version }}
