name: Unit tests
on: [push, pull_request]
jobs:
    boost_1_70_0:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/cache@v2
              with:
                key: boost_1_70_0
                path: tests/tmp/boost_*.tar.bz2
            - run: sudo apt-get install --yes gdb
            - run: python3 tests/run -c -b 1.70.0
